model_hps:
  num_layers: 2             # Number of transformer layers
  emb_dim: 200              # Dimension of word vectors (colexnet)
  num_heads: 10             # Number of attention heads
  dim_feedforward: 800      # Dimension of feed-forward layers
  dropout: 0.1              # Dropout rate
  max_context_size: 256     # Max Context size for the set transformer
  padding_idx: 3610267      # PAD token idx

training_hps:
  batch_size: 256
  lr: 0.0005
  lr_sched_step_size: 5
  lr_sched_gamma: 0.95
  weight_decay: 0.0
  epochs: 120
  augmentation_threshold: 4
  augmentation_min_percentage: 0.5
  augmentation_keep_all_percentage: 0.5
  num_workers: 16            # Number of workers for data loading

notes: >
  Set Former training hyperparameters