model_hps:
  num_heads: 10
  emb_dim: 200
  num_layers: 28
  dropout: 0.4
  max_context_size: 256
  padding_idx: 3610267      # PAD token idx

training_hps:
  batch_size: 256
  lr: 0.0001
  lr_sched_step_size: 10
  lr_sched_gamma: 0.95
  contrastive_temp: 0.25
  loss_lambd: 0.1
  weight_decay: 0
  epochs: 500
  augmentation_threshold: 4
  augmentation_min_percentage: 0.5
  augmentation_keep_all_percentage: 0.5
  num_workers: 16

notes: >
  Set Former training hyperparameters